networks:
  inventory-backend:
    driver: bridge

volumes:
  inventory-mongo-data:

services:
  mongodb:
    networks:
      - inventory-backend
    image: mongo:7.0.6
    container_name: inventory-mongodb
    restart: unless-stopped
    ports:
      - "${MONGODB_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    volumes:
      - inventory-mongo-data:/data/db

  app:
    networks:
      - inventory-backend
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${APP_PORT}:3000"
    depends_on:
      - mongodb
